# Setup
title:               'YEONUALPHA'
tagline:             ''
description:         ''
url:                 https://yeonualpha.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
markdown:            kramdown

# About/contact
author:
  name:              hwanki_jung
  url:               https://yeonualpha.github.io
  email:             infin23@naver.com
  
# github
github:
  repo:              https://github.com/yeonualpha  

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-173940308-1
